version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
